services:
  postgres:
    image: postgres:16
    container_name: security-edge-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: security_edge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - security-network

networks:
  security-network:
    driver: bridge

volumes:
  postgres_data:
  
    